
[env]
term = "xterm-256color"

[colors.bright]
black = "0xbdbdbd"
blue = "0xb1d8f6"
cyan = "0x1ab2a8"
green = "0xbddeab"
magenta = "0xfbdaff"
red = "0xffa1a1"
white = "0xffffff"
yellow = "0xffdca0"

[colors.cursor]
cursor = "0xffa460"
text = "0xffffff"

[colors.normal]
black = "0x929292"
blue = "0x97bedc"
cyan = "0x00988e"
green = "0x94b979"
magenta = "0xe1c0fa"
red = "0xe27373"
white = "0xdedede"
yellow = "0xffba7b"

[colors.primary]
background = "0x090808"
foreground = "0xc6c6c6"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "BitstromWera Nerd Font Mono"
style = "Regular"

[font.italic]
family = "BitstromWera Nerd Font Mono"
style = "Oblique"

[font.bold]
family = "BitstromWera Nerd Font Mono"
style = "Bold"

[font.offset]
x = 0
y = 0

[window]
decorations = "buttonless"
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 8
y = 8

[general]
live_config_reload = true
